#include "stdafx.h"

struct {LPCWSTR id, region;} g_region[] = 
{
	{L"afg", L"Afghanistan"},
	{L"ala", L"Åland Islands"},
	{L"alb", L"Albania"},
	{L"dza", L"Algeria"},
	{L"asm", L"American Samoa"},
	{L"and", L"Andorra"},
	{L"ago", L"Angola"},
	{L"aia", L"Anguilla"},
	{L"ata", L"Antarctica"},
	{L"atg", L"Antigua and Barbuda"},
	{L"arg", L"Argentina"},
	{L"arm", L"Armenia"},
	{L"abw", L"Aruba"},
	{L"aus", L"Australia"},
	{L"aut", L"Austria"},
	{L"aze", L"Azerbaijan"},
	{L"bhs", L"Bahamas"},
	{L"bhr", L"Bahrain"},
	{L"bgd", L"Bangladesh"},
	{L"brb", L"Barbados"},
	{L"blr", L"Belarus"},
	{L"bel", L"Belgium"},
	{L"blz", L"Belize"},
	{L"ben", L"Benin"},
	{L"bmu", L"Bermuda"},
	{L"btn", L"Bhutan"},
	{L"bol", L"Bolivia, Plurinational State of"},
	{L"bes", L"Bonaire, Saint Eustatius and Saba"},
	{L"bih", L"Bosnia and Herzegovina"},
	{L"bwa", L"Botswana"},
	{L"bvt", L"Bouvet Island"},
	{L"bra", L"Brazil"},
	{L"iot", L"British Indian Ocean Territory"},
	{L"brn", L"Brunei Darussalam"},
	{L"bgr", L"Bulgaria"},
	{L"bfa", L"Burkina Faso"},
	{L"bdi", L"Burundi"},
	{L"khm", L"Cambodia"},
	{L"cmr", L"Cameroon"},
	{L"can", L"Canada"},
	{L"cpv", L"Cape Verde"},
	{L"cym", L"Cayman Islands"},
	{L"caf", L"Central African Republic"},
	{L"tcd", L"Chad"},
	{L"chl", L"Chile"},
	{L"chn", L"China"},
	{L"cxr", L"Christmas Island"},
	{L"cck", L"Cocos (Keeling) Islands"},
	{L"col", L"Colombia"},
	{L"com", L"Comoros"},
	{L"cog", L"Congo"},
	{L"cod", L"Congo, the Democratic Republic of the"},
	{L"cok", L"Cook Islands"},
	{L"cri", L"Costa Rica"},
	{L"civ", L"Côte d'Ivoire"},
	{L"hrv", L"Croatia"},
	{L"cub", L"Cuba"},
	{L"cuw", L"Curaçao"},
	{L"cyp", L"Cyprus"},
	{L"cze", L"Czech Republic"},
	{L"dnk", L"Denmark"},
	{L"dji", L"Djibouti"},
	{L"dma", L"Dominica"},
	{L"dom", L"Dominican Republic"},
	{L"ecu", L"Ecuador"},
	{L"egy", L"Egypt"},
	{L"slv", L"El Salvador"},
	{L"gnq", L"Equatorial Guinea"},
	{L"eri", L"Eritrea"},
	{L"est", L"Estonia"},
	{L"eth", L"Ethiopia"},
	{L"flk", L"Falkland Islands (Malvinas)"},
	{L"fro", L"Faroe Islands"},
	{L"fji", L"Fiji"},
	{L"fin", L"Finland"},
	{L"fra", L"France"},
	{L"guf", L"French Guiana"},
	{L"pyf", L"French Polynesia"},
	{L"atf", L"French Southern Territories"},
	{L"gab", L"Gabon"},
	{L"gmb", L"Gambia"},
	{L"geo", L"Georgia"},
	{L"deu", L"Germany"},
	{L"gha", L"Ghana"},
	{L"gib", L"Gibraltar"},
	{L"grc", L"Greece"},
	{L"grl", L"Greenland"},
	{L"grd", L"Grenada"},
	{L"glp", L"Guadeloupe"},
	{L"gum", L"Guam"},
	{L"gtm", L"Guatemala"},
	{L"ggy", L"Guernsey"},
	{L"gin", L"Guinea"},
	{L"gnb", L"Guinea-Bissau"},
	{L"guy", L"Guyana"},
	{L"hti", L"Haiti"},
	{L"hmd", L"Heard Island and McDonald Islands"},
	{L"vat", L"Holy See (Vatican City State)"},
	{L"hnd", L"Honduras"},
	{L"hkg", L"Hong Kong"},
	{L"hun", L"Hungary"},
	{L"isl", L"Iceland"},
	{L"ind", L"India"},
	{L"idn", L"Indonesia"},
	{L"irn", L"Iran, Islamic Republic of"},
	{L"irq", L"Iraq"},
	{L"irl", L"Ireland"},
	{L"imn", L"Isle of Man"},
	{L"isr", L"Israel"},
	{L"ita", L"Italy"},
	{L"jam", L"Jamaica"},
	{L"jpn", L"Japan"},
	{L"jey", L"Jersey"},
	{L"jor", L"Jordan"},
	{L"kaz", L"Kazakhstan"},
	{L"ken", L"Kenya"},
	{L"kir", L"Kiribati"},
	{L"prk", L"Korea, Democratic People's Republic of"},
	{L"kor", L"Korea, Republic of"},
	{L"kwt", L"Kuwait"},
	{L"kgz", L"Kyrgyzstan"},
	{L"lao", L"Lao People's Democratic Republic"},
	{L"lva", L"Latvia"},
	{L"lbn", L"Lebanon"},
	{L"lso", L"Lesotho"},
	{L"lbr", L"Liberia"},
	{L"lby", L"Libyan Arab Jamahiriya"},
	{L"lie", L"Liechtenstein"},
	{L"ltu", L"Lithuania"},
	{L"lux", L"Luxembourg"},
	{L"mac", L"Macao"},
	{L"mkd", L"Macedonia, the former Yugoslav Republic of"},
	{L"mdg", L"Madagascar"},
	{L"mwi", L"Malawi"},
	{L"mys", L"Malaysia"},
	{L"mdv", L"Maldives"},
	{L"mli", L"Mali"},
	{L"mlt", L"Malta"},
	{L"mhl", L"Marshall Islands"},
	{L"mtq", L"Martinique"},
	{L"mrt", L"Mauritania"},
	{L"mus", L"Mauritius"},
	{L"myt", L"Mayotte"},
	{L"mex", L"Mexico"},
	{L"fsm", L"Micronesia, Federated States of"},
	{L"mda", L"Moldova, Republic of"},
	{L"mco", L"Monaco"},
	{L"mng", L"Mongolia"},
	{L"mne", L"Montenegro"},
	{L"msr", L"Montserrat"},
	{L"mar", L"Morocco"},
	{L"moz", L"Mozambique"},
	{L"mmr", L"Myanmar"},
	{L"nam", L"Namibia"},
	{L"nru", L"Nauru"},
	{L"npl", L"Nepal"},
	{L"nld", L"Netherlands"},
	{L"ncl", L"New Caledonia"},
	{L"nzl", L"New Zealand"},
	{L"nic", L"Nicaragua"},
	{L"ner", L"Niger"},
	{L"nga", L"Nigeria"},
	{L"niu", L"Niue"},
	{L"nfk", L"Norfolk Island"},
	{L"mnp", L"Northern Mariana Islands"},
	{L"nor", L"Norway"},
	{L"omn", L"Oman"},
	{L"pak", L"Pakistan"},
	{L"plw", L"Palau"},
	{L"pse", L"Palestinian Territory, Occupied"},
	{L"pan", L"Panama"},
	{L"png", L"Papua New Guinea"},
	{L"pry", L"Paraguay"},
	{L"per", L"Peru"},
	{L"phl", L"Philippines"},
	{L"pcn", L"Pitcairn"},
	{L"pol", L"Poland"},
	{L"prt", L"Portugal"},
	{L"pri", L"Puerto Rico"},
	{L"qat", L"Qatar"},
	{L"reu", L"Réunion"},
	{L"rou", L"Romania"},
	{L"rus", L"Russian Federation"},
	{L"rwa", L"Rwanda"},
	{L"blm", L"Saint Barthélemy"},
	{L"shn", L"Saint Helena, Ascension and Tristan da Cunha"},
	{L"kna", L"Saint Kitts and Nevis"},
	{L"lca", L"Saint Lucia"},
	{L"maf", L"Saint Martin (French part)"},
	{L"spm", L"Saint Pierre and Miquelon"},
	{L"vct", L"Saint Vincent and the Grenadines"},
	{L"wsm", L"Samoa"},
	{L"smr", L"San Marino"},
	{L"stp", L"Sao Tome and Principe"},
	{L"sau", L"Saudi Arabia"},
	{L"sen", L"Senegal"},
	{L"srb", L"Serbia"},
	{L"syc", L"Seychelles"},
	{L"sle", L"Sierra Leone"},
	{L"sgp", L"Singapore"},
	{L"sxm", L"Sint Maarten (Dutch part)"},
	{L"svk", L"Slovakia"},
	{L"svn", L"Slovenia"},
	{L"slb", L"Solomon Islands"},
	{L"som", L"Somalia"},
	{L"zaf", L"South Africa"},
	{L"sgs", L"South Georgia and the South Sandwich Islands"},
	{L"esp", L"Spain"},
	{L"lka", L"Sri Lanka"},
	{L"sdn", L"Sudan"},
	{L"sur", L"Suriname"},
	{L"sjm", L"Svalbard and Jan Mayen"},
	{L"swz", L"Swaziland"},
	{L"swe", L"Sweden"},
	{L"che", L"Switzerland"},
	{L"syr", L"Syrian Arab Republic"},
	{L"twn", L"Taiwan, Province of China"},
	{L"tjk", L"Tajikistan"},
	{L"tza", L"Tanzania, United Republic of"},
	{L"tha", L"Thailand"},
	{L"tls", L"Timor-Leste"},
	{L"tgo", L"Togo"},
	{L"tkl", L"Tokelau"},
	{L"ton", L"Tonga"},
	{L"tto", L"Trinidad and Tobago"},
	{L"tun", L"Tunisia"},
	{L"tur", L"Turkey"},
	{L"tkm", L"Turkmenistan"},
	{L"tca", L"Turks and Caicos Islands"},
	{L"tuv", L"Tuvalu"},
	{L"uga", L"Uganda"},
	{L"ukr", L"Ukraine"},
	{L"are", L"United Arab Emirates"},
	{L"gbr", L"United Kingdom"},
	{L"usa", L"United States"},
	{L"umi", L"United States Minor Outlying Islands"},
	{L"ury", L"Uruguay"},
	{L"uzb", L"Uzbekistan"},
	{L"vut", L"Vanuatu"},
	{L"ven", L"Venezuela, Bolivarian Republic of"},
	{L"vnm", L"Viet Nam"},
	{L"vgb", L"Virgin Islands, British"},
	{L"vir", L"Virgin Islands, U.S."},
	{L"wlf", L"Wallis and Futuna"},
	{L"esh", L"Western Sahara"},
	{L"yem", L"Yemen"},
	{L"zmb", L"Zambia"},
	{L"zwe", L"Zimbabwe"},
	{NULL, NULL},
};

int g_region_count = countof(g_region) - 1;